// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejE0sDjXhUx8iSOHFxhYh_OXvjf24BDY',
    appId: '1:779825959200:web:aa613e240b9e95c64a4745',
    messagingSenderId: '779825959200',
    projectId: 'shelf-life-tracker-27',
    authDomain: 'shelf-life-tracker-27.firebaseapp.com',
    storageBucket: 'shelf-life-tracker-27.firebasestorage.app',
    measurementId: 'G-WE94R174PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQU1bTw9D6XyxmzqD9e6sefHQLh3FIHCs',
    appId: '1:779825959200:android:fe1bd5246b93a1ac4a4745',
    messagingSenderId: '779825959200',
    projectId: 'shelf-life-tracker-27',
    storageBucket: 'shelf-life-tracker-27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGSHwVcq2sCetsE4jjQyZ7pFWeRbUBqyM',
    appId: '1:779825959200:ios:4a21413738ef3b8b4a4745',
    messagingSenderId: '779825959200',
    projectId: 'shelf-life-tracker-27',
    storageBucket: 'shelf-life-tracker-27.firebasestorage.app',
    iosBundleId: 'com.example.shelfLifeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGSHwVcq2sCetsE4jjQyZ7pFWeRbUBqyM',
    appId: '1:779825959200:ios:4a21413738ef3b8b4a4745',
    messagingSenderId: '779825959200',
    projectId: 'shelf-life-tracker-27',
    storageBucket: 'shelf-life-tracker-27.firebasestorage.app',
    iosBundleId: 'com.example.shelfLifeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDejE0sDjXhUx8iSOHFxhYh_OXvjf24BDY',
    appId: '1:779825959200:web:4b13e1ba290d52ed4a4745',
    messagingSenderId: '779825959200',
    projectId: 'shelf-life-tracker-27',
    authDomain: 'shelf-life-tracker-27.firebaseapp.com',
    storageBucket: 'shelf-life-tracker-27.firebasestorage.app',
    measurementId: 'G-G22HMXPN5V',
  );
}
